import java.sql.ResultSet;
import java.sql.Statement;
public class tariff_entry extends javax.swing.JFrame 
{
    Statement stmt=null;
    public tariff_entry() 
    {
        initComponents();
        setTariff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jt2 = new javax.swing.JTextField();
        jt3 = new javax.swing.JTextField();
        jb1 = new javax.swing.JButton();
        jb3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jt5 = new javax.swing.JTextField();
        jt6 = new javax.swing.JTextField();
        jt7 = new javax.swing.JTextField();
        jt11 = new javax.swing.JTextField();
        jt22 = new javax.swing.JTextField();
        jt33 = new javax.swing.JTextField();
        jt44 = new javax.swing.JTextField();
        jt55 = new javax.swing.JTextField();
        jt66 = new javax.swing.JTextField();
        jt77 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jl8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel1.setText("0 - 50");

        jLabel2.setText("51 - 100");

        jLabel3.setText("101 - 200");

        jb1.setText("Submit");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb3.setText("Clear all tariff");
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jLabel4.setText("201 - 300");

        jLabel5.setText("301 - 400");

        jLabel7.setText("401 - 500");

        jLabel8.setText("Above 500");

        jt11.setText("0");

        jt22.setText("0");

        jt33.setText("0");

        jt44.setText("0");

        jt55.setText("0");

        jt66.setText("0");

        jt77.setText("0");

        jLabel9.setText("HIKE");

        jLabel10.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel10.setText("TARIFF DETAIL ENTRY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jl8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb3)
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jt6, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jt3)
                                    .addComponent(jt2)
                                    .addComponent(jt1)
                                    .addComponent(jt5)
                                    .addComponent(jt4)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt77, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt66, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jt55)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jt44, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jt33, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jt22, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jt11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel10)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jt77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jb1)
                .addGap(18, 18, 18)
                .addComponent(jb3)
                .addGap(26, 26, 26)
                .addComponent(jl8)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setTariff()
    {
        try
        {
            dbmsconnection obj=new dbmsconnection();
            stmt=obj.stmt;
            String query="SELECT RATE FROM TARIFF";
            ResultSet rs=stmt.executeQuery(query); 
            float a[]=new float[7];
            int i=0,flag=0;
            while(rs.next())
            {
                a[i++]=rs.getFloat(1);
            }
            jt1.setText(String.valueOf(a[0]));
            jt2.setText(String.valueOf(a[1]));
            jt3.setText(String.valueOf(a[2]));
            jt4.setText(String.valueOf(a[3]));
            jt5.setText(String.valueOf(a[4]));
            jt6.setText(String.valueOf(a[5]));
            jt7.setText(String.valueOf(a[6]));
            
            stmt.close();
            obj.con.close();
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }
    
    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        float a1=Float.parseFloat(jt1.getText());
        float a2=Float.parseFloat(jt2.getText());
        float a3=Float.parseFloat(jt3.getText());
        float a4=Float.parseFloat(jt4.getText());
        float a5=Float.parseFloat(jt5.getText());
        float a6=Float.parseFloat(jt6.getText());
        float a7=Float.parseFloat(jt7.getText());
        
        float a11=Float.parseFloat(jt11.getText());
        float a22=Float.parseFloat(jt22.getText());
        float a33=Float.parseFloat(jt33.getText());
        float a44=Float.parseFloat(jt44.getText());
        float a55=Float.parseFloat(jt55.getText());
        float a66=Float.parseFloat(jt66.getText());
        float a77=Float.parseFloat(jt77.getText());
        try
        {
            dbmsconnection obj=new dbmsconnection();
            stmt=obj.stmt;
            a1+=(a1*(a11/100));
            a2+=(a2*(a22/100));
            a3+=(a3*(a33/100));
            a4+=(a4*(a44/100));
            a5+=(a5*(a55/100));
            a6+=(a6*(a66/100));
            a7+=(a7*(a77/100));
            String query1="UPDATE TARIFF SET RATE ="+a1+" WHERE START_UNIT=0";
            String query2="UPDATE TARIFF SET RATE ="+a2+" WHERE START_UNIT=51";
            String query3="UPDATE TARIFF SET RATE ="+a3+" WHERE START_UNIT=101";
            String query4="UPDATE TARIFF SET RATE ="+a4+" WHERE START_UNIT=201";
            String query5="UPDATE TARIFF SET RATE ="+a5+" WHERE START_UNIT=301";
            String query6="UPDATE TARIFF SET RATE ="+a6+" WHERE START_UNIT=401";
            String query7="UPDATE TARIFF SET RATE ="+a7+" WHERE START_UNIT=501";
        
            int j=0;
            j+=stmt.executeUpdate(query1);
            j+=stmt.executeUpdate(query2);
            j+=stmt.executeUpdate(query3);
            j+=stmt.executeUpdate(query4);
            j+=stmt.executeUpdate(query5);
            j+=stmt.executeUpdate(query6);
            j+=stmt.executeUpdate(query7);
            if(j==7)
            {
                jl8.setText("Updated Successfully");
            }
            else
            {
                jl8.setText("Error");
            }
            stmt.close();
            obj.con.close();
            setTariff();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        
        try
        {
            dbmsconnection obj=new dbmsconnection();
            stmt=obj.stmt;
            String query1="UPDATE TARIFF SET RATE =0";
            int k;
            k=stmt.executeUpdate(query1);
            if(k==7)
                jl8.setText("Rate cleared");
            else    
                jl8.setText("Error");
            stmt.close();
            obj.con.close();
            setTariff();
            
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jb3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(tariff_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(tariff_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(tariff_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(tariff_entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new tariff_entry().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb3;
    private javax.swing.JLabel jl8;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt11;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt22;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt33;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt44;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt55;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt66;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt77;
    // End of variables declaration//GEN-END:variables
}
